create extension if not exists pgcrypto;

create type public.pump_state as enum ('on', 'off');
create type public.control_mode as enum ('automatic', 'manual');
create type public.sensor_status as enum ('initializing', 'healthy', 'timeout', 'out_of_range');
create type public.command_status as enum ('pending', 'delivered', 'acknowledged', 'rejected', 'failed', 'expired');

create table public.borehole_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) between 1 and 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.borehole_devices (
  id uuid primary key default gen_random_uuid(),
  device_code text not null unique check (device_code ~ '^[A-Z0-9_-]{3,64}$'),
  name text not null check (char_length(name) between 1 and 120),
  location_name text check (char_length(location_name) <= 240),
  token_hash text not null,
  firmware_version text not null default 'unknown',
  is_online boolean not null default false,
  last_seen_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.borehole_device_members (
  device_id uuid not null references public.borehole_devices(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'operator', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (device_id, user_id)
);

create table public.borehole_device_settings (
  device_id uuid primary key references public.borehole_devices(id) on delete cascade,
  lower_limit_percent real not null default 60 check (lower_limit_percent between 0 and 99),
  upper_limit_percent real not null default 95 check (upper_limit_percent between 1 and 100),
  usable_tank_depth_cm real not null default 100 check (usable_tank_depth_cm in (20,30,50,100,150,200,250,300,350)),
  mounting_offset_cm real not null default 10 check (mounting_offset_cm between 0 and 100),
  maximum_pump_runtime_seconds integer not null default 1800 check (maximum_pump_runtime_seconds between 30 and 86400),
  telemetry_interval_seconds integer not null default 10 check (telemetry_interval_seconds between 3 and 3600),
  updated_at timestamptz not null default now(),
  check (upper_limit_percent - lower_limit_percent >= 5)
);

create table public.borehole_device_state (
  device_id uuid primary key references public.borehole_devices(id) on delete cascade,
  received_at timestamptz not null default now(),
  distance_cm real,
  water_depth_cm real,
  level_percent real check (level_percent between 0 and 100),
  sensor_status public.sensor_status not null default 'initializing',
  pump_state public.pump_state not null default 'off',
  control_mode public.control_mode not null default 'automatic',
  fault_code text check (char_length(fault_code) <= 80),
  wifi_rssi_dbm integer check (wifi_rssi_dbm between -127 and 0),
  firmware_version text not null default 'unknown'
);

create table public.borehole_events (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.borehole_devices(id) on delete restrict,
  event_type text not null check (event_type in ('pump_started','pump_stopped','fault_raised','fault_cleared','fault_clear_requested','configuration_requested','mode_requested','manual_pump_requested')),
  severity text not null default 'info' check (severity in ('info','warning','critical')),
  message text not null check (char_length(message) between 1 and 500),
  actor_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create table public.borehole_readings (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.borehole_devices(id) on delete restrict,
  received_at timestamptz not null default now(),
  uptime_ms bigint not null check (uptime_ms >= 0),
  distance_cm real,
  water_depth_cm real,
  level_percent real check (level_percent between 0 and 100),
  sensor_status public.sensor_status not null,
  pump_state public.pump_state not null,
  control_mode public.control_mode not null,
  fault_code text check (char_length(fault_code) <= 80),
  wifi_rssi_dbm integer check (wifi_rssi_dbm between -127 and 0),
  firmware_version text not null check (char_length(firmware_version) between 1 and 40)
);

create table public.borehole_commands (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.borehole_devices(id) on delete cascade,
  requested_by uuid not null references auth.users(id) on delete restrict,
  command_type text not null check (command_type in ('set_config', 'set_mode', 'pump', 'clear_fault')),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  status public.command_status not null default 'pending',
  requested_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 minutes'),
  delivered_at timestamptz,
  acknowledged_at timestamptz,
  result_message text check (char_length(result_message) <= 500),
  check (expires_at > requested_at),
  check (expires_at <= requested_at + interval '10 minutes')
);

create index borehole_readings_device_received_idx
  on public.borehole_readings(device_id, received_at desc);
create index borehole_commands_pending_idx
  on public.borehole_commands(device_id, requested_at)
  where status in ('pending', 'delivered');
create index borehole_members_user_idx
  on public.borehole_device_members(user_id, device_id);
create index borehole_events_device_created_idx
  on public.borehole_events(device_id, created_at desc);

alter table public.borehole_profiles enable row level security;
alter table public.borehole_devices enable row level security;
alter table public.borehole_device_members enable row level security;
alter table public.borehole_device_settings enable row level security;
alter table public.borehole_readings enable row level security;
alter table public.borehole_commands enable row level security;
alter table public.borehole_device_state enable row level security;
alter table public.borehole_events enable row level security;

grant select on public.borehole_profiles, public.borehole_devices, public.borehole_device_members,
  public.borehole_device_settings, public.borehole_readings,
  public.borehole_commands, public.borehole_device_state,
  public.borehole_events to authenticated;
grant insert, update on public.borehole_profiles to authenticated;
grant insert on public.borehole_commands to authenticated;
grant usage, select on sequence public.borehole_readings_id_seq,
  public.borehole_events_id_seq to authenticated;

create policy "users read their profile" on public.borehole_profiles
  for select to authenticated using (user_id = (select auth.uid()));
create policy "users create their profile" on public.borehole_profiles
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "users update their profile" on public.borehole_profiles
  for update to authenticated using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "members read their devices" on public.borehole_devices
  for select to authenticated using (exists (
    select 1 from public.borehole_device_members m
    where m.device_id = id and m.user_id = (select auth.uid())
  ));
create policy "members read their memberships" on public.borehole_device_members
  for select to authenticated using (user_id = (select auth.uid()));
create policy "members read device settings" on public.borehole_device_settings
  for select to authenticated using (exists (
    select 1 from public.borehole_device_members m
    where m.device_id = borehole_device_settings.device_id
      and m.user_id = (select auth.uid())
  ));
create policy "members read device telemetry" on public.borehole_readings
  for select to authenticated using (exists (
    select 1 from public.borehole_device_members m
    where m.device_id = borehole_readings.device_id
      and m.user_id = (select auth.uid())
  ));
create policy "members read device commands" on public.borehole_commands
  for select to authenticated using (exists (
    select 1 from public.borehole_device_members m
    where m.device_id = borehole_commands.device_id
      and m.user_id = (select auth.uid())
  ));
create policy "owners and operators create device commands" on public.borehole_commands
  for insert to authenticated with check (
    requested_by = (select auth.uid()) and exists (
      select 1 from public.borehole_device_members m
      where m.device_id = borehole_commands.device_id
        and m.user_id = (select auth.uid())
        and m.role in ('owner', 'operator')
    )
  );
create policy "members read latest device state" on public.borehole_device_state
  for select to authenticated using (exists (
    select 1 from public.borehole_device_members m
    where m.device_id = borehole_device_state.device_id
      and m.user_id = (select auth.uid())
  ));
create policy "members read device events" on public.borehole_events
  for select to authenticated using (exists (
    select 1 from public.borehole_device_members m
    where m.device_id = borehole_events.device_id
      and m.user_id = (select auth.uid())
  ));

alter publication supabase_realtime add table public.borehole_devices;
alter publication supabase_realtime add table public.borehole_readings;
alter publication supabase_realtime add table public.borehole_commands;
alter publication supabase_realtime add table public.borehole_device_state;
alter publication supabase_realtime add table public.borehole_events;

comment on column public.borehole_devices.token_hash is
  'Bcrypt hash only. The original device token must never be stored here.';

create or replace function public.audit_borehole_command()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.borehole_events (
    device_id, event_type, message, actor_user_id, metadata
  ) values (
    new.device_id,
    case new.command_type
      when 'set_config' then 'configuration_requested'
      when 'set_mode' then 'mode_requested'
      when 'clear_fault' then 'fault_clear_requested'
      else 'manual_pump_requested'
    end,
    'Dashboard command requested',
    new.requested_by,
    jsonb_build_object('command_id', new.id, 'command_type', new.command_type)
  );
  return new;
end;
$$;

revoke all on function public.audit_borehole_command() from public;
create trigger audit_borehole_command_insert
  after insert on public.borehole_commands
  for each row execute function public.audit_borehole_command();
